import {
  Building,
  Calendar,
  Globe,
  Grid,
  Hash,
  Layout,
  MapPin,
  Palette,
  ShieldCheck,
  Users,
  Rocket,
  LifeBuoy,
  RefreshCw,
  UserCircle,
  Mail,
  Trophy
} from "lucide-react";

import { moduleRegistry } from "./registry";
import type { ModuleDefinition, ModuleGroup } from "./types";

export const moduleGroups: ModuleGroup[] = [
  { id: "platform", label: "Platform", order: 10 },
  { id: "operations", label: "Operations", order: 20 },
  { id: "people", label: "People", order: 30 },
  { id: "finance", label: "Finance", order: 40 },
  { id: "intelligence", label: "Intelligence", order: 50 },
];

export const modules: ModuleDefinition[] = [
  {
    id: "founder",
    name: "Founder OS",
    description: "Executive cockpit for real-time strategic intelligence.",
    icon: ShieldCheck,
    group: "platform",
    order: 5,
    status: "available",
    basePath: "/modules/founder",
    permission: "platform.founder.view",
  },
  {
    id: "overview",
    name: "Overview",
    description: "Workspace entry point for the operating system.",
    icon: Layout,
    group: "platform",
    order: 10,
    status: "available",
    basePath: "/",
    permission: "platform.dashboard.view",
  },
  {
    id: "organization",
    name: "Organization",
    description: "Configure business foundation, hierarchy and branding.",
    icon: Building,
    group: "platform",
    order: 15,
    status: "available",
    basePath: "/modules/organization",
    permission: "platform.organization.view",
  },
  {
    id: "crm",
    name: "CRM",
    description: "Customer relationships, pipeline and revenue operations.",
    icon: Building,
    group: "operations",
    order: 20,
    status: "available",
    basePath: "/modules/crm",
    permission: "operations.crm.view",
  },
  {
    id: "renewals",
    name: "Renewal Center",
    description: "Manage subscription lifecycles, retention and renewal revenue.",
    icon: RefreshCw,
    group: "operations",
    order: 20.5,
    status: "available",
    basePath: "/modules/renewals",
    permission: "operations.renewals.view",
  },
  {
    id: "customer-portal",
    name: "Customer Portal",
    description: "External-facing portal for customer subscription and support management.",
    icon: UserCircle,
    group: "operations",
    order: 20.6,
    status: "available",
    basePath: "/customer/portal",
    permission: "operations.customer-portal.view",
  },
  {
    id: "activation",
    name: "Activation",
    description: "Enterprise activation queue, SLA management and service onboarding.",
    icon: Rocket,
    group: "operations",
    order: 21,
    status: "available",
    basePath: "/modules/activation",
    permission: "operations.activation.view",
  },
  {
    id: "support",
    name: "Support",
    description: "Ticket management, internal notes and service level agreements.",
    icon: LifeBuoy,
    group: "operations",
    order: 22,
    status: "available",
    basePath: "/modules/support",
    permission: "operations.support.view",
  },
  {
    id: "projects",
    name: "Projects",
    description: "Delivery planning, execution and resource allocation.",
    icon: Grid,
    group: "operations",
    order: 30,
    status: "available",
    basePath: "/modules/projects",
  },
  {
    id: "inventory",
    name: "Inventory",
    description: "Stock, procurement and asset tracking.",
    icon: Grid,
    group: "operations",
    order: 40,
    status: "available",
    basePath: "/modules/inventory",
  },
  {
    id: "users",
    name: "User Management",
    description: "Manage enterprise users, status and organizational assignments.",
    icon: Users,
    group: "people",
    order: 45,
    status: "available",
    basePath: "/modules/users",
    permission: "people.users.view",
  },
  {
    id: "employees",
    name: "Employees",
    description: "Employee records, profiles, and employment lifecycle.",
    icon: Users,
    group: "people",
    order: 47,
    status: "available",
    basePath: "/modules/employees",
    permission: "people.employees.view",
  },
  {
    id: "hrms",
    name: "HRMS",
    description: "Employee lifecycle, payroll, performance and recruitment.",
    icon: ShieldCheck,
    group: "people",
    order: 50,
    status: "available",
    basePath: "/modules/hrms",
    permission: "people.hrms.view",
  },
  {
    id: "finance",
    name: "Finance",
    description: "Accounting, invoicing and financial controls.",
    icon: ShieldCheck,
    group: "finance",
    order: 60,
    status: "available",
    basePath: "/modules/finance",
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "Campaign planning, channels and attribution.",
    icon: Globe,
    group: "operations",
    order: 70,
    status: "planned",
    basePath: "/modules/marketing",
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Cross-module reporting and business intelligence.",
    icon: Hash,
    group: "intelligence",
    order: 80,
    status: "planned",
    basePath: "/modules/analytics",
  },
  {
    id: "automation",
    name: "Automation",
    description: "Workflow orchestration and business rules.",
    icon: Calendar,
    group: "intelligence",
    order: 90,
    status: "planned",
    basePath: "/modules/automation",
  },
  {
    id: "ai",
    name: "AI Studio",
    description: "Assistants, agents and AI-native operations.",
    icon: Palette,
    group: "intelligence",
    order: 100,
    status: "available",
    basePath: "/modules/ai",
  },
  {
    id: "roles",
    name: "Roles & Permissions",
    description: "Define enterprise access control, permission matrices and scoping.",
    icon: ShieldCheck,
    group: "platform",
    order: 105,
    status: "available",
    basePath: "/modules/roles",
    permission: "platform.roles.view",
  },
  {
    id: "admin",
    name: "Admin Studio",
    description: "Centralized no-code configuration, module management and workflows.",
    icon: ShieldCheck,
    group: "platform",
    order: 106,
    status: "available",
    basePath: "/modules/admin",
    permission: "platform.admin.view",
  },
  {
    id: "settings",
    name: "Settings",
    description: "Organisation configuration, roles and module control.",
    icon: Palette,
    group: "platform",
    order: 110,
    status: "available",
    basePath: "/settings",
    permission: "platform.settings.view",
  },
  {
    id: "platform-services",
    name: "Activity Center",
    description: "Shared platform services: Search, Notifications, and Activity Center.",
    icon: Layout,
    group: "platform",
    order: 120,
    status: "available",
    basePath: "/platform/activity",
  },
  {
    id: "security",
    name: "Security Center",
    description: "Monitor authentication, authorization and identity hardening.",
    icon: ShieldCheck,
    group: "platform",
    order: 130,
    status: "available",
    basePath: "/settings/security",
    permission: "platform.security.view",
  },
  {
    id: "communication",
    name: "Comm Center",
    description: "Enterprise communication hub: Email, Templates, and Mailbox management.",
    icon: Mail,
    group: "platform",
    order: 140,
    status: "available",
    basePath: "/communication",
    permission: "communication.view",
  },
  {
    id: "incentives",
    name: "Incentive Engine",
    description: "Manage employee performance rewards and program versioning.",
    icon: Trophy,
    group: "people",
    order: 55,
    status: "available",
    basePath: "/modules/incentives",
    permission: "people.incentives.view",
  },
];

let bootstrapped = false;

export function bootstrapModules(): void {
  if (bootstrapped) return;
  bootstrapped = true;
  moduleRegistry.registerGroups(moduleGroups);
  moduleRegistry.registerAll(modules);
}
