/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as ModulesOrganizationRouteImport } from './routes/modules.organization'
import { Route as ModulesUsersRouteImport } from './routes/modules.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesOrganizationRoute = ModulesOrganizationRouteImport.update({
  id: '/modules/organization',
  path: '/modules/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUsersRoute = ModulesUsersRouteImport.update({
  id: '/modules/users',
  path: '/modules/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/organization'
    | '/modules/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/organization'
    | '/modules/users'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/organization'
    | '/modules/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
  ModulesOrganizationRoute: typeof ModulesOrganizationRoute
  ModulesUsersRoute: typeof ModulesUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/organization': {
      id: '/modules/organization'
      path: '/modules/organization'
      fullPath: '/modules/organization'
      preLoaderRoute: typeof ModulesOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/users': {
      id: '/modules/users'
      path: '/modules/users'
      fullPath: '/modules/users'
      preLoaderRoute: typeof ModulesUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
  ModulesOrganizationRoute: ModulesOrganizationRoute,
  ModulesUsersRoute: ModulesUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
