/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomerPortalRouteImport } from './routes/customer.portal'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as ModulesActivationRouteImport } from './routes/modules.activation'
import { Route as ModulesAdminRouteImport } from './routes/modules.admin'
import { Route as ModulesAiRouteImport } from './routes/modules.ai'
import { Route as ModulesCrmRouteImport } from './routes/modules.crm'
import { Route as ModulesEmployeesRouteImport } from './routes/modules.employees'
import { Route as ModulesFinanceRouteImport } from './routes/modules.finance'
import { Route as ModulesFounderRouteImport } from './routes/modules.founder'
import { Route as ModulesHrmsRouteImport } from './routes/modules.hrms'
import { Route as ModulesIncentivesRouteImport } from './routes/modules.incentives'
import { Route as ModulesInventoryRouteImport } from './routes/modules.inventory'
import { Route as ModulesLeadsRouteImport } from './routes/modules.leads'
import { Route as ModulesOrganizationRouteImport } from './routes/modules.organization'
import { Route as ModulesProjectsRouteImport } from './routes/modules.projects'
import { Route as ModulesRenewalsRouteImport } from './routes/modules.renewals'
import { Route as ModulesRolesRouteImport } from './routes/modules.roles'
import { Route as ModulesSupportRouteImport } from './routes/modules.support'
import { Route as ModulesUsersRouteImport } from './routes/modules.users'
import { Route as PlatformActivityRouteImport } from './routes/platform.activity'
import { Route as PlatformAutomationRouteImport } from './routes/platform.automation'
import { Route as PlatformDataCenterRouteImport } from './routes/platform.data-center'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as AppActivationIndexRouteImport } from './routes/app/activation/index'
import { Route as AppActivationIdRouteImport } from './routes/app/activation/$id'
import { Route as AppActivationAssignmentsRouteImport } from './routes/app/activation/assignments'
import { Route as AppActivationHistoryRouteImport } from './routes/app/activation/history'
import { Route as AppActivationQueueRouteImport } from './routes/app/activation/queue'
import { Route as AppCrmIndexRouteImport } from './routes/app/crm/index'
import { Route as AppCrmCallbacksRouteImport } from './routes/app/crm/callbacks'
import { Route as AppCrmCustomersRouteImport } from './routes/app/crm/customers'
import { Route as AppCrmFollowUpsRouteImport } from './routes/app/crm/follow-ups'
import { Route as AppCrmLeadPoolRouteImport } from './routes/app/crm/lead-pool'
import { Route as AppCrmMyLeadsRouteImport } from './routes/app/crm/my-leads'
import { Route as AppFinanceIndexRouteImport } from './routes/app/finance/index'
import { Route as AppFinanceExpensesRouteImport } from './routes/app/finance/expenses'
import { Route as AppFinanceInvoicesRouteImport } from './routes/app/finance/invoices'
import { Route as AppFinancePaymentsRouteImport } from './routes/app/finance/payments'
import { Route as AppFinancePayrollRouteImport } from './routes/app/finance/payroll'
import { Route as AppFinanceReconciliationRouteImport } from './routes/app/finance/reconciliation'
import { Route as AppFinanceRefundsRouteImport } from './routes/app/finance/refunds'
import { Route as AppFinanceReportsRouteImport } from './routes/app/finance/reports'
import { Route as AppFinanceRevenueRouteImport } from './routes/app/finance/revenue'
import { Route as AppFinanceTransactionsRouteImport } from './routes/app/finance/transactions'
import { Route as AppSalesIndexRouteImport } from './routes/app/sales/index'
import { Route as AppSalesDealsRouteImport } from './routes/app/sales/deals'
import { Route as AppSalesInvoicesRouteImport } from './routes/app/sales/invoices'
import { Route as AppSalesPaymentLinksRouteImport } from './routes/app/sales/payment-links'
import { Route as AppSalesPaymentsRouteImport } from './routes/app/sales/payments'
import { Route as AppSalesPlansRouteImport } from './routes/app/sales/plans'
import { Route as AppSalesReportsRouteImport } from './routes/app/sales/reports'
import { Route as AppSupportIndexRouteImport } from './routes/app/support/index'
import { Route as AppSupportCustomersRouteImport } from './routes/app/support/customers'
import { Route as AppSupportKnowledgeBaseRouteImport } from './routes/app/support/knowledge-base'
import { Route as AppSupportReportsRouteImport } from './routes/app/support/reports'
import { Route as AppSupportTicketsRouteImport } from './routes/app/support/tickets'
import { Route as ModulesAdminAuditRouteImport } from './routes/modules/admin/audit'
import { Route as ModulesAdminBrandingRouteImport } from './routes/modules/admin/branding'
import { Route as ModulesAdminBusinessRouteImport } from './routes/modules/admin/business'
import { Route as ModulesAdminCrmRouteImport } from './routes/modules/admin/crm'
import { Route as ModulesAdminDataRouteImport } from './routes/modules/admin/data'
import { Route as ModulesAdminEmployeesRouteImport } from './routes/modules/admin/employees'
import { Route as ModulesAdminIncentivesRouteImport } from './routes/modules/admin/incentives'
import { Route as ModulesAdminIntegrationsRouteImport } from './routes/modules/admin/integrations'
import { Route as ModulesAdminModulesRouteImport } from './routes/modules/admin/modules'
import { Route as ModulesAdminPoliciesRouteImport } from './routes/modules/admin/policies'
import { Route as ModulesAdminRolesRouteImport } from './routes/modules/admin/roles'
import { Route as ModulesAdminSalesRouteImport } from './routes/modules/admin/sales'
import { Route as ModulesAdminSecurityRouteImport } from './routes/modules/admin/security'
import { Route as ModulesAdminSystemRouteImport } from './routes/modules/admin/system'
import { Route as ModulesAdminWorkflowsRouteImport } from './routes/modules/admin/workflows'
import { Route as ModulesCrmAssignmentsRouteImport } from './routes/modules.crm.assignments'
import { Route as ModulesCrmDuplicatesRouteImport } from './routes/modules.crm.duplicates'
import { Route as ModulesCrmForecastRouteImport } from './routes/modules.crm.forecast'
import { Route as ModulesCrmProspectRouteImport } from './routes/modules/crm/prospect'
import { Route as ModulesCrmQueuesRouteImport } from './routes/modules.crm.queues'
import { Route as ModulesHrmsEmployeeRouteImport } from './routes/modules/hrms/employee'
import { Route as PublicConfirmationsTokenRouteImport } from './routes/public.confirmations.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer/portal',
  path: '/customer/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesActivationRoute = ModulesActivationRouteImport.update({
  id: '/modules/activation',
  path: '/modules/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesAdminRoute = ModulesAdminRouteImport.update({
  id: '/modules/admin',
  path: '/modules/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesAiRoute = ModulesAiRouteImport.update({
  id: '/modules/ai',
  path: '/modules/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesCrmRoute = ModulesCrmRouteImport.update({
  id: '/modules/crm',
  path: '/modules/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesEmployeesRoute = ModulesEmployeesRouteImport.update({
  id: '/modules/employees',
  path: '/modules/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesFinanceRoute = ModulesFinanceRouteImport.update({
  id: '/modules/finance',
  path: '/modules/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesFounderRoute = ModulesFounderRouteImport.update({
  id: '/modules/founder',
  path: '/modules/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesHrmsRoute = ModulesHrmsRouteImport.update({
  id: '/modules/hrms',
  path: '/modules/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIncentivesRoute = ModulesIncentivesRouteImport.update({
  id: '/modules/incentives',
  path: '/modules/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesInventoryRoute = ModulesInventoryRouteImport.update({
  id: '/modules/inventory',
  path: '/modules/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesLeadsRoute = ModulesLeadsRouteImport.update({
  id: '/modules/leads',
  path: '/modules/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesOrganizationRoute = ModulesOrganizationRouteImport.update({
  id: '/modules/organization',
  path: '/modules/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesProjectsRoute = ModulesProjectsRouteImport.update({
  id: '/modules/projects',
  path: '/modules/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRenewalsRoute = ModulesRenewalsRouteImport.update({
  id: '/modules/renewals',
  path: '/modules/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRolesRoute = ModulesRolesRouteImport.update({
  id: '/modules/roles',
  path: '/modules/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSupportRoute = ModulesSupportRouteImport.update({
  id: '/modules/support',
  path: '/modules/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUsersRoute = ModulesUsersRouteImport.update({
  id: '/modules/users',
  path: '/modules/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformActivityRoute = PlatformActivityRouteImport.update({
  id: '/platform/activity',
  path: '/platform/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAutomationRoute = PlatformAutomationRouteImport.update({
  id: '/platform/automation',
  path: '/platform/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDataCenterRoute = PlatformDataCenterRouteImport.update({
  id: '/platform/data-center',
  path: '/platform/data-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const AppActivationIndexRoute = AppActivationIndexRouteImport.update({
  id: '/activation/',
  path: '/activation/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationIdRoute = AppActivationIdRouteImport.update({
  id: '/activation/$id',
  path: '/activation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationAssignmentsRoute =
  AppActivationAssignmentsRouteImport.update({
    id: '/activation/assignments',
    path: '/activation/assignments',
    getParentRoute: () => AppRoute,
  } as any)
const AppActivationHistoryRoute = AppActivationHistoryRouteImport.update({
  id: '/activation/history',
  path: '/activation/history',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationQueueRoute = AppActivationQueueRouteImport.update({
  id: '/activation/queue',
  path: '/activation/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCallbacksRoute = AppCrmCallbacksRouteImport.update({
  id: '/crm/callbacks',
  path: '/crm/callbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmFollowUpsRoute = AppCrmFollowUpsRouteImport.update({
  id: '/crm/follow-ups',
  path: '/crm/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadPoolRoute = AppCrmLeadPoolRouteImport.update({
  id: '/crm/lead-pool',
  path: '/crm/lead-pool',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmMyLeadsRoute = AppCrmMyLeadsRouteImport.update({
  id: '/crm/my-leads',
  path: '/crm/my-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePayrollRoute = AppFinancePayrollRouteImport.update({
  id: '/finance/payroll',
  path: '/finance/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReconciliationRoute =
  AppFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceRefundsRoute = AppFinanceRefundsRouteImport.update({
  id: '/finance/refunds',
  path: '/finance/refunds',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRevenueRoute = AppFinanceRevenueRouteImport.update({
  id: '/finance/revenue',
  path: '/finance/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceTransactionsRoute = AppFinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesDealsRoute = AppSalesDealsRouteImport.update({
  id: '/sales/deals',
  path: '/sales/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInvoicesRoute = AppSalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesPaymentLinksRoute = AppSalesPaymentLinksRouteImport.update({
  id: '/sales/payment-links',
  path: '/sales/payment-links',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesPaymentsRoute = AppSalesPaymentsRouteImport.update({
  id: '/sales/payments',
  path: '/sales/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesPlansRoute = AppSalesPlansRouteImport.update({
  id: '/sales/plans',
  path: '/sales/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesReportsRoute = AppSalesReportsRouteImport.update({
  id: '/sales/reports',
  path: '/sales/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportCustomersRoute = AppSupportCustomersRouteImport.update({
  id: '/support/customers',
  path: '/support/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportKnowledgeBaseRoute = AppSupportKnowledgeBaseRouteImport.update({
  id: '/support/knowledge-base',
  path: '/support/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportReportsRoute = AppSupportReportsRouteImport.update({
  id: '/support/reports',
  path: '/support/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketsRoute = AppSupportTicketsRouteImport.update({
  id: '/support/tickets',
  path: '/support/tickets',
  getParentRoute: () => AppRoute,
} as any)
const ModulesAdminAuditRoute = ModulesAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminBrandingRoute = ModulesAdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminBusinessRoute = ModulesAdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminCrmRoute = ModulesAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminDataRoute = ModulesAdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminEmployeesRoute = ModulesAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminIncentivesRoute = ModulesAdminIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminIntegrationsRoute =
  ModulesAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ModulesAdminRoute,
  } as any)
const ModulesAdminModulesRoute = ModulesAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminPoliciesRoute = ModulesAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminRolesRoute = ModulesAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminSalesRoute = ModulesAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminSecurityRoute = ModulesAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminSystemRoute = ModulesAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesAdminWorkflowsRoute = ModulesAdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ModulesAdminRoute,
} as any)
const ModulesCrmAssignmentsRoute = ModulesCrmAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => ModulesCrmRoute,
} as any)
const ModulesCrmDuplicatesRoute = ModulesCrmDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => ModulesCrmRoute,
} as any)
const ModulesCrmForecastRoute = ModulesCrmForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => ModulesCrmRoute,
} as any)
const ModulesCrmProspectRoute = ModulesCrmProspectRouteImport.update({
  id: '/prospect',
  path: '/prospect',
  getParentRoute: () => ModulesCrmRoute,
} as any)
const ModulesCrmQueuesRoute = ModulesCrmQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => ModulesCrmRoute,
} as any)
const ModulesHrmsEmployeeRoute = ModulesHrmsEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => ModulesHrmsRoute,
} as any)
const PublicConfirmationsTokenRoute =
  PublicConfirmationsTokenRouteImport.update({
    id: '/public/confirmations/$token',
    path: '/public/confirmations/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customer/portal': typeof CustomerPortalRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/activation': typeof ModulesActivationRoute
  '/modules/admin': typeof ModulesAdminRouteWithChildren
  '/modules/ai': typeof ModulesAiRoute
  '/modules/crm': typeof ModulesCrmRouteWithChildren
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/founder': typeof ModulesFounderRoute
  '/modules/hrms': typeof ModulesHrmsRouteWithChildren
  '/modules/incentives': typeof ModulesIncentivesRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/projects': typeof ModulesProjectsRoute
  '/modules/renewals': typeof ModulesRenewalsRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/support': typeof ModulesSupportRoute
  '/modules/users': typeof ModulesUsersRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/automation': typeof PlatformAutomationRoute
  '/platform/data-center': typeof PlatformDataCenterRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/app/activation/$id': typeof AppActivationIdRoute
  '/app/activation/assignments': typeof AppActivationAssignmentsRoute
  '/app/activation/history': typeof AppActivationHistoryRoute
  '/app/activation/queue': typeof AppActivationQueueRoute
  '/app/crm/callbacks': typeof AppCrmCallbacksRoute
  '/app/crm/customers': typeof AppCrmCustomersRoute
  '/app/crm/follow-ups': typeof AppCrmFollowUpsRoute
  '/app/crm/lead-pool': typeof AppCrmLeadPoolRoute
  '/app/crm/my-leads': typeof AppCrmMyLeadsRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/finance/payroll': typeof AppFinancePayrollRoute
  '/app/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/app/finance/refunds': typeof AppFinanceRefundsRoute
  '/app/finance/reports': typeof AppFinanceReportsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/sales/deals': typeof AppSalesDealsRoute
  '/app/sales/invoices': typeof AppSalesInvoicesRoute
  '/app/sales/payment-links': typeof AppSalesPaymentLinksRoute
  '/app/sales/payments': typeof AppSalesPaymentsRoute
  '/app/sales/plans': typeof AppSalesPlansRoute
  '/app/sales/reports': typeof AppSalesReportsRoute
  '/app/support/customers': typeof AppSupportCustomersRoute
  '/app/support/knowledge-base': typeof AppSupportKnowledgeBaseRoute
  '/app/support/reports': typeof AppSupportReportsRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/modules/admin/audit': typeof ModulesAdminAuditRoute
  '/modules/admin/branding': typeof ModulesAdminBrandingRoute
  '/modules/admin/business': typeof ModulesAdminBusinessRoute
  '/modules/admin/crm': typeof ModulesAdminCrmRoute
  '/modules/admin/data': typeof ModulesAdminDataRoute
  '/modules/admin/employees': typeof ModulesAdminEmployeesRoute
  '/modules/admin/incentives': typeof ModulesAdminIncentivesRoute
  '/modules/admin/integrations': typeof ModulesAdminIntegrationsRoute
  '/modules/admin/modules': typeof ModulesAdminModulesRoute
  '/modules/admin/policies': typeof ModulesAdminPoliciesRoute
  '/modules/admin/roles': typeof ModulesAdminRolesRoute
  '/modules/admin/sales': typeof ModulesAdminSalesRoute
  '/modules/admin/security': typeof ModulesAdminSecurityRoute
  '/modules/admin/system': typeof ModulesAdminSystemRoute
  '/modules/admin/workflows': typeof ModulesAdminWorkflowsRoute
  '/modules/crm/assignments': typeof ModulesCrmAssignmentsRoute
  '/modules/crm/duplicates': typeof ModulesCrmDuplicatesRoute
  '/modules/crm/forecast': typeof ModulesCrmForecastRoute
  '/modules/crm/prospect': typeof ModulesCrmProspectRoute
  '/modules/crm/queues': typeof ModulesCrmQueuesRoute
  '/modules/hrms/employee': typeof ModulesHrmsEmployeeRoute
  '/public/confirmations/$token': typeof PublicConfirmationsTokenRoute
  '/app/activation/': typeof AppActivationIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/support/': typeof AppSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customer/portal': typeof CustomerPortalRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/activation': typeof ModulesActivationRoute
  '/modules/admin': typeof ModulesAdminRouteWithChildren
  '/modules/ai': typeof ModulesAiRoute
  '/modules/crm': typeof ModulesCrmRouteWithChildren
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/founder': typeof ModulesFounderRoute
  '/modules/hrms': typeof ModulesHrmsRouteWithChildren
  '/modules/incentives': typeof ModulesIncentivesRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/projects': typeof ModulesProjectsRoute
  '/modules/renewals': typeof ModulesRenewalsRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/support': typeof ModulesSupportRoute
  '/modules/users': typeof ModulesUsersRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/automation': typeof PlatformAutomationRoute
  '/platform/data-center': typeof PlatformDataCenterRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/app/activation/$id': typeof AppActivationIdRoute
  '/app/activation/assignments': typeof AppActivationAssignmentsRoute
  '/app/activation/history': typeof AppActivationHistoryRoute
  '/app/activation/queue': typeof AppActivationQueueRoute
  '/app/crm/callbacks': typeof AppCrmCallbacksRoute
  '/app/crm/customers': typeof AppCrmCustomersRoute
  '/app/crm/follow-ups': typeof AppCrmFollowUpsRoute
  '/app/crm/lead-pool': typeof AppCrmLeadPoolRoute
  '/app/crm/my-leads': typeof AppCrmMyLeadsRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/finance/payroll': typeof AppFinancePayrollRoute
  '/app/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/app/finance/refunds': typeof AppFinanceRefundsRoute
  '/app/finance/reports': typeof AppFinanceReportsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/sales/deals': typeof AppSalesDealsRoute
  '/app/sales/invoices': typeof AppSalesInvoicesRoute
  '/app/sales/payment-links': typeof AppSalesPaymentLinksRoute
  '/app/sales/payments': typeof AppSalesPaymentsRoute
  '/app/sales/plans': typeof AppSalesPlansRoute
  '/app/sales/reports': typeof AppSalesReportsRoute
  '/app/support/customers': typeof AppSupportCustomersRoute
  '/app/support/knowledge-base': typeof AppSupportKnowledgeBaseRoute
  '/app/support/reports': typeof AppSupportReportsRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/modules/admin/audit': typeof ModulesAdminAuditRoute
  '/modules/admin/branding': typeof ModulesAdminBrandingRoute
  '/modules/admin/business': typeof ModulesAdminBusinessRoute
  '/modules/admin/crm': typeof ModulesAdminCrmRoute
  '/modules/admin/data': typeof ModulesAdminDataRoute
  '/modules/admin/employees': typeof ModulesAdminEmployeesRoute
  '/modules/admin/incentives': typeof ModulesAdminIncentivesRoute
  '/modules/admin/integrations': typeof ModulesAdminIntegrationsRoute
  '/modules/admin/modules': typeof ModulesAdminModulesRoute
  '/modules/admin/policies': typeof ModulesAdminPoliciesRoute
  '/modules/admin/roles': typeof ModulesAdminRolesRoute
  '/modules/admin/sales': typeof ModulesAdminSalesRoute
  '/modules/admin/security': typeof ModulesAdminSecurityRoute
  '/modules/admin/system': typeof ModulesAdminSystemRoute
  '/modules/admin/workflows': typeof ModulesAdminWorkflowsRoute
  '/modules/crm/assignments': typeof ModulesCrmAssignmentsRoute
  '/modules/crm/duplicates': typeof ModulesCrmDuplicatesRoute
  '/modules/crm/forecast': typeof ModulesCrmForecastRoute
  '/modules/crm/prospect': typeof ModulesCrmProspectRoute
  '/modules/crm/queues': typeof ModulesCrmQueuesRoute
  '/modules/hrms/employee': typeof ModulesHrmsEmployeeRoute
  '/public/confirmations/$token': typeof PublicConfirmationsTokenRoute
  '/app/activation': typeof AppActivationIndexRoute
  '/app/crm': typeof AppCrmIndexRoute
  '/app/finance': typeof AppFinanceIndexRoute
  '/app/sales': typeof AppSalesIndexRoute
  '/app/support': typeof AppSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customer/portal': typeof CustomerPortalRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/activation': typeof ModulesActivationRoute
  '/modules/admin': typeof ModulesAdminRouteWithChildren
  '/modules/ai': typeof ModulesAiRoute
  '/modules/crm': typeof ModulesCrmRouteWithChildren
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/founder': typeof ModulesFounderRoute
  '/modules/hrms': typeof ModulesHrmsRouteWithChildren
  '/modules/incentives': typeof ModulesIncentivesRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/projects': typeof ModulesProjectsRoute
  '/modules/renewals': typeof ModulesRenewalsRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/support': typeof ModulesSupportRoute
  '/modules/users': typeof ModulesUsersRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/automation': typeof PlatformAutomationRoute
  '/platform/data-center': typeof PlatformDataCenterRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/app/activation/$id': typeof AppActivationIdRoute
  '/app/activation/assignments': typeof AppActivationAssignmentsRoute
  '/app/activation/history': typeof AppActivationHistoryRoute
  '/app/activation/queue': typeof AppActivationQueueRoute
  '/app/crm/callbacks': typeof AppCrmCallbacksRoute
  '/app/crm/customers': typeof AppCrmCustomersRoute
  '/app/crm/follow-ups': typeof AppCrmFollowUpsRoute
  '/app/crm/lead-pool': typeof AppCrmLeadPoolRoute
  '/app/crm/my-leads': typeof AppCrmMyLeadsRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/finance/payroll': typeof AppFinancePayrollRoute
  '/app/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/app/finance/refunds': typeof AppFinanceRefundsRoute
  '/app/finance/reports': typeof AppFinanceReportsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/app/sales/deals': typeof AppSalesDealsRoute
  '/app/sales/invoices': typeof AppSalesInvoicesRoute
  '/app/sales/payment-links': typeof AppSalesPaymentLinksRoute
  '/app/sales/payments': typeof AppSalesPaymentsRoute
  '/app/sales/plans': typeof AppSalesPlansRoute
  '/app/sales/reports': typeof AppSalesReportsRoute
  '/app/support/customers': typeof AppSupportCustomersRoute
  '/app/support/knowledge-base': typeof AppSupportKnowledgeBaseRoute
  '/app/support/reports': typeof AppSupportReportsRoute
  '/app/support/tickets': typeof AppSupportTicketsRoute
  '/modules/admin/audit': typeof ModulesAdminAuditRoute
  '/modules/admin/branding': typeof ModulesAdminBrandingRoute
  '/modules/admin/business': typeof ModulesAdminBusinessRoute
  '/modules/admin/crm': typeof ModulesAdminCrmRoute
  '/modules/admin/data': typeof ModulesAdminDataRoute
  '/modules/admin/employees': typeof ModulesAdminEmployeesRoute
  '/modules/admin/incentives': typeof ModulesAdminIncentivesRoute
  '/modules/admin/integrations': typeof ModulesAdminIntegrationsRoute
  '/modules/admin/modules': typeof ModulesAdminModulesRoute
  '/modules/admin/policies': typeof ModulesAdminPoliciesRoute
  '/modules/admin/roles': typeof ModulesAdminRolesRoute
  '/modules/admin/sales': typeof ModulesAdminSalesRoute
  '/modules/admin/security': typeof ModulesAdminSecurityRoute
  '/modules/admin/system': typeof ModulesAdminSystemRoute
  '/modules/admin/workflows': typeof ModulesAdminWorkflowsRoute
  '/modules/crm/assignments': typeof ModulesCrmAssignmentsRoute
  '/modules/crm/duplicates': typeof ModulesCrmDuplicatesRoute
  '/modules/crm/forecast': typeof ModulesCrmForecastRoute
  '/modules/crm/prospect': typeof ModulesCrmProspectRoute
  '/modules/crm/queues': typeof ModulesCrmQueuesRoute
  '/modules/hrms/employee': typeof ModulesHrmsEmployeeRoute
  '/public/confirmations/$token': typeof PublicConfirmationsTokenRoute
  '/app/activation/': typeof AppActivationIndexRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/support/': typeof AppSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/communication'
    | '/settings'
    | '/customer/portal'
    | '/modules/$moduleId'
    | '/modules/activation'
    | '/modules/admin'
    | '/modules/ai'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/founder'
    | '/modules/hrms'
    | '/modules/incentives'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/projects'
    | '/modules/renewals'
    | '/modules/roles'
    | '/modules/support'
    | '/modules/users'
    | '/platform/activity'
    | '/platform/automation'
    | '/platform/data-center'
    | '/settings/audit'
    | '/settings/security'
    | '/app/activation/$id'
    | '/app/activation/assignments'
    | '/app/activation/history'
    | '/app/activation/queue'
    | '/app/crm/callbacks'
    | '/app/crm/customers'
    | '/app/crm/follow-ups'
    | '/app/crm/lead-pool'
    | '/app/crm/my-leads'
    | '/app/finance/expenses'
    | '/app/finance/invoices'
    | '/app/finance/payments'
    | '/app/finance/payroll'
    | '/app/finance/reconciliation'
    | '/app/finance/refunds'
    | '/app/finance/reports'
    | '/app/finance/revenue'
    | '/app/finance/transactions'
    | '/app/sales/deals'
    | '/app/sales/invoices'
    | '/app/sales/payment-links'
    | '/app/sales/payments'
    | '/app/sales/plans'
    | '/app/sales/reports'
    | '/app/support/customers'
    | '/app/support/knowledge-base'
    | '/app/support/reports'
    | '/app/support/tickets'
    | '/modules/admin/audit'
    | '/modules/admin/branding'
    | '/modules/admin/business'
    | '/modules/admin/crm'
    | '/modules/admin/data'
    | '/modules/admin/employees'
    | '/modules/admin/incentives'
    | '/modules/admin/integrations'
    | '/modules/admin/modules'
    | '/modules/admin/policies'
    | '/modules/admin/roles'
    | '/modules/admin/sales'
    | '/modules/admin/security'
    | '/modules/admin/system'
    | '/modules/admin/workflows'
    | '/modules/crm/assignments'
    | '/modules/crm/duplicates'
    | '/modules/crm/forecast'
    | '/modules/crm/prospect'
    | '/modules/crm/queues'
    | '/modules/hrms/employee'
    | '/public/confirmations/$token'
    | '/app/activation/'
    | '/app/crm/'
    | '/app/finance/'
    | '/app/sales/'
    | '/app/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/communication'
    | '/settings'
    | '/customer/portal'
    | '/modules/$moduleId'
    | '/modules/activation'
    | '/modules/admin'
    | '/modules/ai'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/founder'
    | '/modules/hrms'
    | '/modules/incentives'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/projects'
    | '/modules/renewals'
    | '/modules/roles'
    | '/modules/support'
    | '/modules/users'
    | '/platform/activity'
    | '/platform/automation'
    | '/platform/data-center'
    | '/settings/audit'
    | '/settings/security'
    | '/app/activation/$id'
    | '/app/activation/assignments'
    | '/app/activation/history'
    | '/app/activation/queue'
    | '/app/crm/callbacks'
    | '/app/crm/customers'
    | '/app/crm/follow-ups'
    | '/app/crm/lead-pool'
    | '/app/crm/my-leads'
    | '/app/finance/expenses'
    | '/app/finance/invoices'
    | '/app/finance/payments'
    | '/app/finance/payroll'
    | '/app/finance/reconciliation'
    | '/app/finance/refunds'
    | '/app/finance/reports'
    | '/app/finance/revenue'
    | '/app/finance/transactions'
    | '/app/sales/deals'
    | '/app/sales/invoices'
    | '/app/sales/payment-links'
    | '/app/sales/payments'
    | '/app/sales/plans'
    | '/app/sales/reports'
    | '/app/support/customers'
    | '/app/support/knowledge-base'
    | '/app/support/reports'
    | '/app/support/tickets'
    | '/modules/admin/audit'
    | '/modules/admin/branding'
    | '/modules/admin/business'
    | '/modules/admin/crm'
    | '/modules/admin/data'
    | '/modules/admin/employees'
    | '/modules/admin/incentives'
    | '/modules/admin/integrations'
    | '/modules/admin/modules'
    | '/modules/admin/policies'
    | '/modules/admin/roles'
    | '/modules/admin/sales'
    | '/modules/admin/security'
    | '/modules/admin/system'
    | '/modules/admin/workflows'
    | '/modules/crm/assignments'
    | '/modules/crm/duplicates'
    | '/modules/crm/forecast'
    | '/modules/crm/prospect'
    | '/modules/crm/queues'
    | '/modules/hrms/employee'
    | '/public/confirmations/$token'
    | '/app/activation'
    | '/app/crm'
    | '/app/finance'
    | '/app/sales'
    | '/app/support'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/communication'
    | '/settings'
    | '/customer/portal'
    | '/modules/$moduleId'
    | '/modules/activation'
    | '/modules/admin'
    | '/modules/ai'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/founder'
    | '/modules/hrms'
    | '/modules/incentives'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/projects'
    | '/modules/renewals'
    | '/modules/roles'
    | '/modules/support'
    | '/modules/users'
    | '/platform/activity'
    | '/platform/automation'
    | '/platform/data-center'
    | '/settings/audit'
    | '/settings/security'
    | '/app/activation/$id'
    | '/app/activation/assignments'
    | '/app/activation/history'
    | '/app/activation/queue'
    | '/app/crm/callbacks'
    | '/app/crm/customers'
    | '/app/crm/follow-ups'
    | '/app/crm/lead-pool'
    | '/app/crm/my-leads'
    | '/app/finance/expenses'
    | '/app/finance/invoices'
    | '/app/finance/payments'
    | '/app/finance/payroll'
    | '/app/finance/reconciliation'
    | '/app/finance/refunds'
    | '/app/finance/reports'
    | '/app/finance/revenue'
    | '/app/finance/transactions'
    | '/app/sales/deals'
    | '/app/sales/invoices'
    | '/app/sales/payment-links'
    | '/app/sales/payments'
    | '/app/sales/plans'
    | '/app/sales/reports'
    | '/app/support/customers'
    | '/app/support/knowledge-base'
    | '/app/support/reports'
    | '/app/support/tickets'
    | '/modules/admin/audit'
    | '/modules/admin/branding'
    | '/modules/admin/business'
    | '/modules/admin/crm'
    | '/modules/admin/data'
    | '/modules/admin/employees'
    | '/modules/admin/incentives'
    | '/modules/admin/integrations'
    | '/modules/admin/modules'
    | '/modules/admin/policies'
    | '/modules/admin/roles'
    | '/modules/admin/sales'
    | '/modules/admin/security'
    | '/modules/admin/system'
    | '/modules/admin/workflows'
    | '/modules/crm/assignments'
    | '/modules/crm/duplicates'
    | '/modules/crm/forecast'
    | '/modules/crm/prospect'
    | '/modules/crm/queues'
    | '/modules/hrms/employee'
    | '/public/confirmations/$token'
    | '/app/activation/'
    | '/app/crm/'
    | '/app/finance/'
    | '/app/sales/'
    | '/app/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunicationRoute: typeof CommunicationRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  CustomerPortalRoute: typeof CustomerPortalRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
  ModulesActivationRoute: typeof ModulesActivationRoute
  ModulesAdminRoute: typeof ModulesAdminRouteWithChildren
  ModulesAiRoute: typeof ModulesAiRoute
  ModulesCrmRoute: typeof ModulesCrmRouteWithChildren
  ModulesEmployeesRoute: typeof ModulesEmployeesRoute
  ModulesFinanceRoute: typeof ModulesFinanceRoute
  ModulesFounderRoute: typeof ModulesFounderRoute
  ModulesHrmsRoute: typeof ModulesHrmsRouteWithChildren
  ModulesIncentivesRoute: typeof ModulesIncentivesRoute
  ModulesInventoryRoute: typeof ModulesInventoryRoute
  ModulesLeadsRoute: typeof ModulesLeadsRoute
  ModulesOrganizationRoute: typeof ModulesOrganizationRoute
  ModulesProjectsRoute: typeof ModulesProjectsRoute
  ModulesRenewalsRoute: typeof ModulesRenewalsRoute
  ModulesRolesRoute: typeof ModulesRolesRoute
  ModulesSupportRoute: typeof ModulesSupportRoute
  ModulesUsersRoute: typeof ModulesUsersRoute
  PlatformActivityRoute: typeof PlatformActivityRoute
  PlatformAutomationRoute: typeof PlatformAutomationRoute
  PlatformDataCenterRoute: typeof PlatformDataCenterRoute
  PublicConfirmationsTokenRoute: typeof PublicConfirmationsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/portal': {
      id: '/customer/portal'
      path: '/customer/portal'
      fullPath: '/customer/portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/activation': {
      id: '/modules/activation'
      path: '/modules/activation'
      fullPath: '/modules/activation'
      preLoaderRoute: typeof ModulesActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/admin': {
      id: '/modules/admin'
      path: '/modules/admin'
      fullPath: '/modules/admin'
      preLoaderRoute: typeof ModulesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/ai': {
      id: '/modules/ai'
      path: '/modules/ai'
      fullPath: '/modules/ai'
      preLoaderRoute: typeof ModulesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/crm': {
      id: '/modules/crm'
      path: '/modules/crm'
      fullPath: '/modules/crm'
      preLoaderRoute: typeof ModulesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/employees': {
      id: '/modules/employees'
      path: '/modules/employees'
      fullPath: '/modules/employees'
      preLoaderRoute: typeof ModulesEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/finance': {
      id: '/modules/finance'
      path: '/modules/finance'
      fullPath: '/modules/finance'
      preLoaderRoute: typeof ModulesFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/founder': {
      id: '/modules/founder'
      path: '/modules/founder'
      fullPath: '/modules/founder'
      preLoaderRoute: typeof ModulesFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/hrms': {
      id: '/modules/hrms'
      path: '/modules/hrms'
      fullPath: '/modules/hrms'
      preLoaderRoute: typeof ModulesHrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/incentives': {
      id: '/modules/incentives'
      path: '/modules/incentives'
      fullPath: '/modules/incentives'
      preLoaderRoute: typeof ModulesIncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/inventory': {
      id: '/modules/inventory'
      path: '/modules/inventory'
      fullPath: '/modules/inventory'
      preLoaderRoute: typeof ModulesInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/leads': {
      id: '/modules/leads'
      path: '/modules/leads'
      fullPath: '/modules/leads'
      preLoaderRoute: typeof ModulesLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/organization': {
      id: '/modules/organization'
      path: '/modules/organization'
      fullPath: '/modules/organization'
      preLoaderRoute: typeof ModulesOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/projects': {
      id: '/modules/projects'
      path: '/modules/projects'
      fullPath: '/modules/projects'
      preLoaderRoute: typeof ModulesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/renewals': {
      id: '/modules/renewals'
      path: '/modules/renewals'
      fullPath: '/modules/renewals'
      preLoaderRoute: typeof ModulesRenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/roles': {
      id: '/modules/roles'
      path: '/modules/roles'
      fullPath: '/modules/roles'
      preLoaderRoute: typeof ModulesRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/support': {
      id: '/modules/support'
      path: '/modules/support'
      fullPath: '/modules/support'
      preLoaderRoute: typeof ModulesSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/users': {
      id: '/modules/users'
      path: '/modules/users'
      fullPath: '/modules/users'
      preLoaderRoute: typeof ModulesUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/activity': {
      id: '/platform/activity'
      path: '/platform/activity'
      fullPath: '/platform/activity'
      preLoaderRoute: typeof PlatformActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/automation': {
      id: '/platform/automation'
      path: '/platform/automation'
      fullPath: '/platform/automation'
      preLoaderRoute: typeof PlatformAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/data-center': {
      id: '/platform/data-center'
      path: '/platform/data-center'
      fullPath: '/platform/data-center'
      preLoaderRoute: typeof PlatformDataCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/activation/': {
      id: '/app/activation/'
      path: '/activation'
      fullPath: '/app/activation/'
      preLoaderRoute: typeof AppActivationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation/$id': {
      id: '/app/activation/$id'
      path: '/activation/$id'
      fullPath: '/app/activation/$id'
      preLoaderRoute: typeof AppActivationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation/assignments': {
      id: '/app/activation/assignments'
      path: '/activation/assignments'
      fullPath: '/app/activation/assignments'
      preLoaderRoute: typeof AppActivationAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation/history': {
      id: '/app/activation/history'
      path: '/activation/history'
      fullPath: '/app/activation/history'
      preLoaderRoute: typeof AppActivationHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activation/queue': {
      id: '/app/activation/queue'
      path: '/activation/queue'
      fullPath: '/app/activation/queue'
      preLoaderRoute: typeof AppActivationQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/': {
      id: '/app/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/callbacks': {
      id: '/app/crm/callbacks'
      path: '/crm/callbacks'
      fullPath: '/app/crm/callbacks'
      preLoaderRoute: typeof AppCrmCallbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/customers': {
      id: '/app/crm/customers'
      path: '/crm/customers'
      fullPath: '/app/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/follow-ups': {
      id: '/app/crm/follow-ups'
      path: '/crm/follow-ups'
      fullPath: '/app/crm/follow-ups'
      preLoaderRoute: typeof AppCrmFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/lead-pool': {
      id: '/app/crm/lead-pool'
      path: '/crm/lead-pool'
      fullPath: '/app/crm/lead-pool'
      preLoaderRoute: typeof AppCrmLeadPoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/my-leads': {
      id: '/app/crm/my-leads'
      path: '/crm/my-leads'
      fullPath: '/app/crm/my-leads'
      preLoaderRoute: typeof AppCrmMyLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/': {
      id: '/app/finance/'
      path: '/finance'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/expenses': {
      id: '/app/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/app/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/invoices': {
      id: '/app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/app/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/payments': {
      id: '/app/finance/payments'
      path: '/finance/payments'
      fullPath: '/app/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/payroll': {
      id: '/app/finance/payroll'
      path: '/finance/payroll'
      fullPath: '/app/finance/payroll'
      preLoaderRoute: typeof AppFinancePayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/reconciliation': {
      id: '/app/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/app/finance/reconciliation'
      preLoaderRoute: typeof AppFinanceReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/refunds': {
      id: '/app/finance/refunds'
      path: '/finance/refunds'
      fullPath: '/app/finance/refunds'
      preLoaderRoute: typeof AppFinanceRefundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/reports': {
      id: '/app/finance/reports'
      path: '/finance/reports'
      fullPath: '/app/finance/reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/revenue': {
      id: '/app/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/app/finance/revenue'
      preLoaderRoute: typeof AppFinanceRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/transactions': {
      id: '/app/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/app/finance/transactions'
      preLoaderRoute: typeof AppFinanceTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/': {
      id: '/app/sales/'
      path: '/sales'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/deals': {
      id: '/app/sales/deals'
      path: '/sales/deals'
      fullPath: '/app/sales/deals'
      preLoaderRoute: typeof AppSalesDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/invoices': {
      id: '/app/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/app/sales/invoices'
      preLoaderRoute: typeof AppSalesInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/payment-links': {
      id: '/app/sales/payment-links'
      path: '/sales/payment-links'
      fullPath: '/app/sales/payment-links'
      preLoaderRoute: typeof AppSalesPaymentLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/payments': {
      id: '/app/sales/payments'
      path: '/sales/payments'
      fullPath: '/app/sales/payments'
      preLoaderRoute: typeof AppSalesPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/plans': {
      id: '/app/sales/plans'
      path: '/sales/plans'
      fullPath: '/app/sales/plans'
      preLoaderRoute: typeof AppSalesPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/reports': {
      id: '/app/sales/reports'
      path: '/sales/reports'
      fullPath: '/app/sales/reports'
      preLoaderRoute: typeof AppSalesReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/': {
      id: '/app/support/'
      path: '/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/customers': {
      id: '/app/support/customers'
      path: '/support/customers'
      fullPath: '/app/support/customers'
      preLoaderRoute: typeof AppSupportCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/knowledge-base': {
      id: '/app/support/knowledge-base'
      path: '/support/knowledge-base'
      fullPath: '/app/support/knowledge-base'
      preLoaderRoute: typeof AppSupportKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/reports': {
      id: '/app/support/reports'
      path: '/support/reports'
      fullPath: '/app/support/reports'
      preLoaderRoute: typeof AppSupportReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support/tickets': {
      id: '/app/support/tickets'
      path: '/support/tickets'
      fullPath: '/app/support/tickets'
      preLoaderRoute: typeof AppSupportTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/modules/admin/audit': {
      id: '/modules/admin/audit'
      path: '/audit'
      fullPath: '/modules/admin/audit'
      preLoaderRoute: typeof ModulesAdminAuditRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/branding': {
      id: '/modules/admin/branding'
      path: '/branding'
      fullPath: '/modules/admin/branding'
      preLoaderRoute: typeof ModulesAdminBrandingRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/business': {
      id: '/modules/admin/business'
      path: '/business'
      fullPath: '/modules/admin/business'
      preLoaderRoute: typeof ModulesAdminBusinessRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/crm': {
      id: '/modules/admin/crm'
      path: '/crm'
      fullPath: '/modules/admin/crm'
      preLoaderRoute: typeof ModulesAdminCrmRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/data': {
      id: '/modules/admin/data'
      path: '/data'
      fullPath: '/modules/admin/data'
      preLoaderRoute: typeof ModulesAdminDataRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/employees': {
      id: '/modules/admin/employees'
      path: '/employees'
      fullPath: '/modules/admin/employees'
      preLoaderRoute: typeof ModulesAdminEmployeesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/incentives': {
      id: '/modules/admin/incentives'
      path: '/incentives'
      fullPath: '/modules/admin/incentives'
      preLoaderRoute: typeof ModulesAdminIncentivesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/integrations': {
      id: '/modules/admin/integrations'
      path: '/integrations'
      fullPath: '/modules/admin/integrations'
      preLoaderRoute: typeof ModulesAdminIntegrationsRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/modules': {
      id: '/modules/admin/modules'
      path: '/modules'
      fullPath: '/modules/admin/modules'
      preLoaderRoute: typeof ModulesAdminModulesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/policies': {
      id: '/modules/admin/policies'
      path: '/policies'
      fullPath: '/modules/admin/policies'
      preLoaderRoute: typeof ModulesAdminPoliciesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/roles': {
      id: '/modules/admin/roles'
      path: '/roles'
      fullPath: '/modules/admin/roles'
      preLoaderRoute: typeof ModulesAdminRolesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/sales': {
      id: '/modules/admin/sales'
      path: '/sales'
      fullPath: '/modules/admin/sales'
      preLoaderRoute: typeof ModulesAdminSalesRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/security': {
      id: '/modules/admin/security'
      path: '/security'
      fullPath: '/modules/admin/security'
      preLoaderRoute: typeof ModulesAdminSecurityRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/system': {
      id: '/modules/admin/system'
      path: '/system'
      fullPath: '/modules/admin/system'
      preLoaderRoute: typeof ModulesAdminSystemRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/admin/workflows': {
      id: '/modules/admin/workflows'
      path: '/workflows'
      fullPath: '/modules/admin/workflows'
      preLoaderRoute: typeof ModulesAdminWorkflowsRouteImport
      parentRoute: typeof ModulesAdminRoute
    }
    '/modules/crm/assignments': {
      id: '/modules/crm/assignments'
      path: '/assignments'
      fullPath: '/modules/crm/assignments'
      preLoaderRoute: typeof ModulesCrmAssignmentsRouteImport
      parentRoute: typeof ModulesCrmRoute
    }
    '/modules/crm/duplicates': {
      id: '/modules/crm/duplicates'
      path: '/duplicates'
      fullPath: '/modules/crm/duplicates'
      preLoaderRoute: typeof ModulesCrmDuplicatesRouteImport
      parentRoute: typeof ModulesCrmRoute
    }
    '/modules/crm/forecast': {
      id: '/modules/crm/forecast'
      path: '/forecast'
      fullPath: '/modules/crm/forecast'
      preLoaderRoute: typeof ModulesCrmForecastRouteImport
      parentRoute: typeof ModulesCrmRoute
    }
    '/modules/crm/prospect': {
      id: '/modules/crm/prospect'
      path: '/prospect'
      fullPath: '/modules/crm/prospect'
      preLoaderRoute: typeof ModulesCrmProspectRouteImport
      parentRoute: typeof ModulesCrmRoute
    }
    '/modules/crm/queues': {
      id: '/modules/crm/queues'
      path: '/queues'
      fullPath: '/modules/crm/queues'
      preLoaderRoute: typeof ModulesCrmQueuesRouteImport
      parentRoute: typeof ModulesCrmRoute
    }
    '/modules/hrms/employee': {
      id: '/modules/hrms/employee'
      path: '/employee'
      fullPath: '/modules/hrms/employee'
      preLoaderRoute: typeof ModulesHrmsEmployeeRouteImport
      parentRoute: typeof ModulesHrmsRoute
    }
    '/public/confirmations/$token': {
      id: '/public/confirmations/$token'
      path: '/public/confirmations/$token'
      fullPath: '/public/confirmations/$token'
      preLoaderRoute: typeof PublicConfirmationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivationIdRoute: typeof AppActivationIdRoute
  AppActivationAssignmentsRoute: typeof AppActivationAssignmentsRoute
  AppActivationHistoryRoute: typeof AppActivationHistoryRoute
  AppActivationQueueRoute: typeof AppActivationQueueRoute
  AppCrmCallbacksRoute: typeof AppCrmCallbacksRoute
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmFollowUpsRoute: typeof AppCrmFollowUpsRoute
  AppCrmLeadPoolRoute: typeof AppCrmLeadPoolRoute
  AppCrmMyLeadsRoute: typeof AppCrmMyLeadsRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppFinancePayrollRoute: typeof AppFinancePayrollRoute
  AppFinanceReconciliationRoute: typeof AppFinanceReconciliationRoute
  AppFinanceRefundsRoute: typeof AppFinanceRefundsRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppFinanceRevenueRoute: typeof AppFinanceRevenueRoute
  AppFinanceTransactionsRoute: typeof AppFinanceTransactionsRoute
  AppSalesDealsRoute: typeof AppSalesDealsRoute
  AppSalesInvoicesRoute: typeof AppSalesInvoicesRoute
  AppSalesPaymentLinksRoute: typeof AppSalesPaymentLinksRoute
  AppSalesPaymentsRoute: typeof AppSalesPaymentsRoute
  AppSalesPlansRoute: typeof AppSalesPlansRoute
  AppSalesReportsRoute: typeof AppSalesReportsRoute
  AppSupportCustomersRoute: typeof AppSupportCustomersRoute
  AppSupportKnowledgeBaseRoute: typeof AppSupportKnowledgeBaseRoute
  AppSupportReportsRoute: typeof AppSupportReportsRoute
  AppSupportTicketsRoute: typeof AppSupportTicketsRoute
  AppActivationIndexRoute: typeof AppActivationIndexRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivationIdRoute: AppActivationIdRoute,
  AppActivationAssignmentsRoute: AppActivationAssignmentsRoute,
  AppActivationHistoryRoute: AppActivationHistoryRoute,
  AppActivationQueueRoute: AppActivationQueueRoute,
  AppCrmCallbacksRoute: AppCrmCallbacksRoute,
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmFollowUpsRoute: AppCrmFollowUpsRoute,
  AppCrmLeadPoolRoute: AppCrmLeadPoolRoute,
  AppCrmMyLeadsRoute: AppCrmMyLeadsRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppFinancePayrollRoute: AppFinancePayrollRoute,
  AppFinanceReconciliationRoute: AppFinanceReconciliationRoute,
  AppFinanceRefundsRoute: AppFinanceRefundsRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppFinanceRevenueRoute: AppFinanceRevenueRoute,
  AppFinanceTransactionsRoute: AppFinanceTransactionsRoute,
  AppSalesDealsRoute: AppSalesDealsRoute,
  AppSalesInvoicesRoute: AppSalesInvoicesRoute,
  AppSalesPaymentLinksRoute: AppSalesPaymentLinksRoute,
  AppSalesPaymentsRoute: AppSalesPaymentsRoute,
  AppSalesPlansRoute: AppSalesPlansRoute,
  AppSalesReportsRoute: AppSalesReportsRoute,
  AppSupportCustomersRoute: AppSupportCustomersRoute,
  AppSupportKnowledgeBaseRoute: AppSupportKnowledgeBaseRoute,
  AppSupportReportsRoute: AppSupportReportsRoute,
  AppSupportTicketsRoute: AppSupportTicketsRoute,
  AppActivationIndexRoute: AppActivationIndexRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsRouteChildren {
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ModulesAdminRouteChildren {
  ModulesAdminAuditRoute: typeof ModulesAdminAuditRoute
  ModulesAdminBrandingRoute: typeof ModulesAdminBrandingRoute
  ModulesAdminBusinessRoute: typeof ModulesAdminBusinessRoute
  ModulesAdminCrmRoute: typeof ModulesAdminCrmRoute
  ModulesAdminDataRoute: typeof ModulesAdminDataRoute
  ModulesAdminEmployeesRoute: typeof ModulesAdminEmployeesRoute
  ModulesAdminIncentivesRoute: typeof ModulesAdminIncentivesRoute
  ModulesAdminIntegrationsRoute: typeof ModulesAdminIntegrationsRoute
  ModulesAdminModulesRoute: typeof ModulesAdminModulesRoute
  ModulesAdminPoliciesRoute: typeof ModulesAdminPoliciesRoute
  ModulesAdminRolesRoute: typeof ModulesAdminRolesRoute
  ModulesAdminSalesRoute: typeof ModulesAdminSalesRoute
  ModulesAdminSecurityRoute: typeof ModulesAdminSecurityRoute
  ModulesAdminSystemRoute: typeof ModulesAdminSystemRoute
  ModulesAdminWorkflowsRoute: typeof ModulesAdminWorkflowsRoute
}

const ModulesAdminRouteChildren: ModulesAdminRouteChildren = {
  ModulesAdminAuditRoute: ModulesAdminAuditRoute,
  ModulesAdminBrandingRoute: ModulesAdminBrandingRoute,
  ModulesAdminBusinessRoute: ModulesAdminBusinessRoute,
  ModulesAdminCrmRoute: ModulesAdminCrmRoute,
  ModulesAdminDataRoute: ModulesAdminDataRoute,
  ModulesAdminEmployeesRoute: ModulesAdminEmployeesRoute,
  ModulesAdminIncentivesRoute: ModulesAdminIncentivesRoute,
  ModulesAdminIntegrationsRoute: ModulesAdminIntegrationsRoute,
  ModulesAdminModulesRoute: ModulesAdminModulesRoute,
  ModulesAdminPoliciesRoute: ModulesAdminPoliciesRoute,
  ModulesAdminRolesRoute: ModulesAdminRolesRoute,
  ModulesAdminSalesRoute: ModulesAdminSalesRoute,
  ModulesAdminSecurityRoute: ModulesAdminSecurityRoute,
  ModulesAdminSystemRoute: ModulesAdminSystemRoute,
  ModulesAdminWorkflowsRoute: ModulesAdminWorkflowsRoute,
}

const ModulesAdminRouteWithChildren = ModulesAdminRoute._addFileChildren(
  ModulesAdminRouteChildren,
)

interface ModulesCrmRouteChildren {
  ModulesCrmAssignmentsRoute: typeof ModulesCrmAssignmentsRoute
  ModulesCrmDuplicatesRoute: typeof ModulesCrmDuplicatesRoute
  ModulesCrmForecastRoute: typeof ModulesCrmForecastRoute
  ModulesCrmProspectRoute: typeof ModulesCrmProspectRoute
  ModulesCrmQueuesRoute: typeof ModulesCrmQueuesRoute
}

const ModulesCrmRouteChildren: ModulesCrmRouteChildren = {
  ModulesCrmAssignmentsRoute: ModulesCrmAssignmentsRoute,
  ModulesCrmDuplicatesRoute: ModulesCrmDuplicatesRoute,
  ModulesCrmForecastRoute: ModulesCrmForecastRoute,
  ModulesCrmProspectRoute: ModulesCrmProspectRoute,
  ModulesCrmQueuesRoute: ModulesCrmQueuesRoute,
}

const ModulesCrmRouteWithChildren = ModulesCrmRoute._addFileChildren(
  ModulesCrmRouteChildren,
)

interface ModulesHrmsRouteChildren {
  ModulesHrmsEmployeeRoute: typeof ModulesHrmsEmployeeRoute
}

const ModulesHrmsRouteChildren: ModulesHrmsRouteChildren = {
  ModulesHrmsEmployeeRoute: ModulesHrmsEmployeeRoute,
}

const ModulesHrmsRouteWithChildren = ModulesHrmsRoute._addFileChildren(
  ModulesHrmsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunicationRoute: CommunicationRoute,
  SettingsRoute: SettingsRouteWithChildren,
  CustomerPortalRoute: CustomerPortalRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
  ModulesActivationRoute: ModulesActivationRoute,
  ModulesAdminRoute: ModulesAdminRouteWithChildren,
  ModulesAiRoute: ModulesAiRoute,
  ModulesCrmRoute: ModulesCrmRouteWithChildren,
  ModulesEmployeesRoute: ModulesEmployeesRoute,
  ModulesFinanceRoute: ModulesFinanceRoute,
  ModulesFounderRoute: ModulesFounderRoute,
  ModulesHrmsRoute: ModulesHrmsRouteWithChildren,
  ModulesIncentivesRoute: ModulesIncentivesRoute,
  ModulesInventoryRoute: ModulesInventoryRoute,
  ModulesLeadsRoute: ModulesLeadsRoute,
  ModulesOrganizationRoute: ModulesOrganizationRoute,
  ModulesProjectsRoute: ModulesProjectsRoute,
  ModulesRenewalsRoute: ModulesRenewalsRoute,
  ModulesRolesRoute: ModulesRolesRoute,
  ModulesSupportRoute: ModulesSupportRoute,
  ModulesUsersRoute: ModulesUsersRoute,
  PlatformActivityRoute: PlatformActivityRoute,
  PlatformAutomationRoute: PlatformAutomationRoute,
  PlatformDataCenterRoute: PlatformDataCenterRoute,
  PublicConfirmationsTokenRoute: PublicConfirmationsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
