/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as ModulesCrmRouteImport } from './routes/modules.crm'
import { Route as ModulesEmployeesRouteImport } from './routes/modules.employees'
import { Route as ModulesFinanceRouteImport } from './routes/modules.finance'
import { Route as ModulesHrmsRouteImport } from './routes/modules.hrms'
import { Route as ModulesInventoryRouteImport } from './routes/modules.inventory'
import { Route as ModulesLeadsRouteImport } from './routes/modules.leads'
import { Route as ModulesOrganizationRouteImport } from './routes/modules.organization'
import { Route as ModulesRolesRouteImport } from './routes/modules.roles'
import { Route as ModulesUsersRouteImport } from './routes/modules.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesCrmRoute = ModulesCrmRouteImport.update({
  id: '/modules/crm',
  path: '/modules/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesEmployeesRoute = ModulesEmployeesRouteImport.update({
  id: '/modules/employees',
  path: '/modules/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesFinanceRoute = ModulesFinanceRouteImport.update({
  id: '/modules/finance',
  path: '/modules/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesHrmsRoute = ModulesHrmsRouteImport.update({
  id: '/modules/hrms',
  path: '/modules/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesInventoryRoute = ModulesInventoryRouteImport.update({
  id: '/modules/inventory',
  path: '/modules/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesLeadsRoute = ModulesLeadsRouteImport.update({
  id: '/modules/leads',
  path: '/modules/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesOrganizationRoute = ModulesOrganizationRouteImport.update({
  id: '/modules/organization',
  path: '/modules/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRolesRoute = ModulesRolesRouteImport.update({
  id: '/modules/roles',
  path: '/modules/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUsersRoute = ModulesUsersRouteImport.update({
  id: '/modules/users',
  path: '/modules/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/crm': typeof ModulesCrmRoute
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/hrms': typeof ModulesHrmsRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/crm': typeof ModulesCrmRoute
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/hrms': typeof ModulesHrmsRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/modules/crm': typeof ModulesCrmRoute
  '/modules/employees': typeof ModulesEmployeesRoute
  '/modules/finance': typeof ModulesFinanceRoute
  '/modules/hrms': typeof ModulesHrmsRoute
  '/modules/inventory': typeof ModulesInventoryRoute
  '/modules/leads': typeof ModulesLeadsRoute
  '/modules/organization': typeof ModulesOrganizationRoute
  '/modules/roles': typeof ModulesRolesRoute
  '/modules/users': typeof ModulesUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/hrms'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/roles'
    | '/modules/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/hrms'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/roles'
    | '/modules/users'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/modules/$moduleId'
    | '/modules/crm'
    | '/modules/employees'
    | '/modules/finance'
    | '/modules/hrms'
    | '/modules/inventory'
    | '/modules/leads'
    | '/modules/organization'
    | '/modules/roles'
    | '/modules/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
  ModulesCrmRoute: typeof ModulesCrmRoute
  ModulesEmployeesRoute: typeof ModulesEmployeesRoute
  ModulesFinanceRoute: typeof ModulesFinanceRoute
  ModulesHrmsRoute: typeof ModulesHrmsRoute
  ModulesInventoryRoute: typeof ModulesInventoryRoute
  ModulesLeadsRoute: typeof ModulesLeadsRoute
  ModulesOrganizationRoute: typeof ModulesOrganizationRoute
  ModulesRolesRoute: typeof ModulesRolesRoute
  ModulesUsersRoute: typeof ModulesUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/crm': {
      id: '/modules/crm'
      path: '/modules/crm'
      fullPath: '/modules/crm'
      preLoaderRoute: typeof ModulesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/employees': {
      id: '/modules/employees'
      path: '/modules/employees'
      fullPath: '/modules/employees'
      preLoaderRoute: typeof ModulesEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/finance': {
      id: '/modules/finance'
      path: '/modules/finance'
      fullPath: '/modules/finance'
      preLoaderRoute: typeof ModulesFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/hrms': {
      id: '/modules/hrms'
      path: '/modules/hrms'
      fullPath: '/modules/hrms'
      preLoaderRoute: typeof ModulesHrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/inventory': {
      id: '/modules/inventory'
      path: '/modules/inventory'
      fullPath: '/modules/inventory'
      preLoaderRoute: typeof ModulesInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/leads': {
      id: '/modules/leads'
      path: '/modules/leads'
      fullPath: '/modules/leads'
      preLoaderRoute: typeof ModulesLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/organization': {
      id: '/modules/organization'
      path: '/modules/organization'
      fullPath: '/modules/organization'
      preLoaderRoute: typeof ModulesOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/roles': {
      id: '/modules/roles'
      path: '/modules/roles'
      fullPath: '/modules/roles'
      preLoaderRoute: typeof ModulesRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/users': {
      id: '/modules/users'
      path: '/modules/users'
      fullPath: '/modules/users'
      preLoaderRoute: typeof ModulesUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
  ModulesCrmRoute: ModulesCrmRoute,
  ModulesEmployeesRoute: ModulesEmployeesRoute,
  ModulesFinanceRoute: ModulesFinanceRoute,
  ModulesHrmsRoute: ModulesHrmsRoute,
  ModulesInventoryRoute: ModulesInventoryRoute,
  ModulesLeadsRoute: ModulesLeadsRoute,
  ModulesOrganizationRoute: ModulesOrganizationRoute,
  ModulesRolesRoute: ModulesRolesRoute,
  ModulesUsersRoute: ModulesUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
